[package]
name = "rust-json-api"
version = "0.1.0"
authors = ["Alex Barry <alex.barry@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde_derive = "1.0.91"
serde_json = "1.0"
serde = "1.0.91"
